### ISSUE TITLE
☂️ JetBrains plugin 1.0

### ISSUE THREAD

**Issue by victor-teles** [biomejs/biome-intellij#14]
### Description

This issue provides a high-level overview of the development of Biome JetBrains plugin version 1.0 and tracks the progress of individual tasks.

## Tasks:

- [x] https://github.com/biomejs/biome/discussions/1052 @victor-teles 
- [x] Enable support for textDocument/formatting in IDEs >2023.3 (https://youtrack.jetbrains.com/issue/IDEA-334150)
- [x] Run the binary without NodeJs interpreter (This is needed to run native binaries when a custom binary path is set)
- [ ] Improve the footer status widget actions
 - `Configure Biome`
 - `Restart Biome Service`
- [x] Support for Yarn PnP @victor-teles 
- [x] Improve auto-save configuration description

## Repository tasks

- [ ] Add IntelliJ Plugin Verifier to GitHub workflows
- [ ] Add automatic changelog to plugin's release notes @nhedger 
- [x] Move the plugin to its [own repository](https://github.com/biomejs/biome-intellij) @nhedger 

**Want to contribute?** Let us know if you are interested! We will assign you to the task to prevent several people from working on the same issue. Don't worry, we can unassign you later if you are no longer interested in the task! Read our [intellij contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z#intellij-plugin-development)

Want to see something else in 1.0? let us know 👇

**Comment by whjvenyl** [comment]
Great work so far.
An additional addition I'd like to see is the current configuration for the Save-Action as seen here for prettier.

![CleanShot 2024-01-08 at 14 40 38@2x](https://github.com/biomejs/biome-intellij/assets/1174049/e457d78e-8a5f-4311-bfbe-dfce4bb26be3)

**Comment by victor-teles** [comment]
@whjvenyl Thank you for the feedback and for testing the nightly version 🤞
I'll add your suggestion to the task list.
